name: Deploy to Server via FTP

on:
  push:
    branches:
      - 2.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.digitalexcellencegroup.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /
        git-ftp-args: --insecure # Add any additional arguments you need
